- name: Get system info from Nokia router
  hosts: all
  #gather_facts: no
  tasks:
  - name: show device info
    nokia.sros.device_info:    
    register: response

  - name: Debug output
    debug:
      var: response

