- name: Get system info from Nokia router
  hosts: all
  gather_facts: no
  connection: network_cli

  collections:
    - nokia.sros

  tasks:
    - name: Run show version on remote devices
      cli_command:
        commands: show version

    # - sros_command:
    #     commands: show version
    #     provider: "{{ cli }}"

      # nokia.srlinux.cli:
      #   commands:
      #   - show version
      # register: response
      #nokia.sros.command:
#      community.network.sros_command:
#        commands:
#          - show version
##      nokia.sros.device_info:    
