- name: Get system info from Nokia router
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show version on remote devices
      #nokia.sros.command:
      community.network.sros_command:
        commands:
          - show version
#      nokia.sros.device_info:    
