- name: Test di ping ICMP
  hosts: all
  gather_facts: true
  tasks:

    - name: Stampare il nome dell'host corrente
      ansible.builtin.debug:
        msg: "Sto eseguendo il playbook su: {{ inventory_hostname }}"

    - name: Eseguire un ping ICMP
      ansible.builtin.ping:
#        data: ping_result

    - name: show output
      ansible.builtin.debug:
        msg: "Risultato per {{ inventory_hostname }}: {{ ping }}"
