- name: Test di ping ICMP
  hosts: all
  gather_facts: true
  tasks:

    - name: Stampare il nome dell'host corrente
      ansible.builtin.debug:
        msg: "Sto eseguendo il playbook su: {{ inventory_hostname }} ({{ ansible_host }}) - {{ ansible_user }}"

#    - name: Eseguire un ping ICMP
#      ansible.builtin.ping:
#      register: ping_result
          

#    - name: show output
#      ansible.builtin.debug:
#        msg: "Risultato per {{ inventory_hostname }} ({{ ansible_host }}) - {{ ansible_user }}: {{ ping_result }}"
